variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  NEXT_TELEMETRY_DISABLED: '1'
  node_version: ^10.10.0

stages:
  - stage: Build
    jobs:
      - job: build
        pool:
          vmImage: 'windows-2019'
        steps:
          - script: echo $(Agent.BuildDirectory)
          - script: dir
          - script: dir $(System.DefaultWorkingDirectory)
          - script: echo $(Build.SourceVersion)
          - powershell: Get-MpComputerStatus
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: 'Install Node.js'
          - task: Cache@2
            inputs:
              # use deterministic cache key that is specific
              # to this test run
              key: $(Build.SourceVersion)
              path: $(System.DefaultWorkingDirectory)
            displayName: Cache Build
          - script: |
              yarn install --frozen-lockfile --check-files
            displayName: 'Install dependencies'

  - stage: Test
    dependsOn: Build
    jobs:
      - job: test_chrome_integration
        pool:
          vmImage: 'windows-2019'
        steps:
          - checkout: none
          - script: |
              wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value
            displayName: 'List Chrome version'
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: 'Install Node.js'
          - task: Cache@2
            inputs:
              # use deterministic cache key that is specific
              # to this test run
              key: $(Build.SourceVersion)
              path: $(System.DefaultWorkingDirectory)
            displayName: Cache Build
          - script: |
              yarn testonly --testPathPattern "cli/test" -t "should exit with code 0"
            displayName: 'Run tests'
